authors = ["Aaron Trowbridge <aaron.j.trowbridge@gmail.com>"]
name = "LevyProcesses"
uuid = "0f701704-5f36-4da1-aa7a-9292f71e42b2"
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
